### ISSUE TITLE
(Low Priority) citus_94 packages don't seem to exist on Amazon Linux

### ISSUE THREAD

**Issue by sumedhpathak** [citusdata/packaging#10]
@begriffs reports the same for other RHEL/CentOS variants too.

Repro:
1. Start fresh Amazon Linux
2. `sudo yum install -y https://download.postgresql.org/pub/repos/yum/9.4/redhat/rhel-6-x86_64/pgdg-ami201503-94-9.4-2.noarch.rpm`
   (Link obtained from: http://yum.postgresql.org/repopackages.php#pg94)
3. `sudo yum install -y citus_94`

Output:

```
[ec2-user@ip-10-186-27-244 ~]$ sudo yum install -y citus_94
Loaded plugins: priorities, update-motd, upgrade-helper
43 packages excluded due to repository priority protections
No package citus_94 available.
Error: Nothing to do
```

This is low priority since we've now deprecated 9.4 support from 5.2 onwards, but recording for posterity and information. The Citus 9.4 packages seem to exist just fine in Ubuntu. Our expectation was they would also exist in the RHEL repo's, so it might be worth understanding why.

**Comment by jasonmp85** [comment]
OK, looked into it and it appears we might have never had PostgreSQL 9.4 builds? I'm not sure why:

```
.
└── rpm
    └── redhat
        ├── 9.5
        │   └── citus
        │       ├── EL-6
        │       │   └── citus.spec
        │       ├── EL-7
        │       │   └── citus.spec
        │       ├── F-22
        │       │   └── citus.spec
        │       ├── F-23
        │       │   └── citus.spec
        │       └── F-24
        │           └── citus.spec
        └── 9.6
            └── citus
                ├── EL-6
                │   └── citus.spec
                ├── EL-7
                │   └── citus.spec
                ├── F-22
                │   └── citus.spec
                ├── F-23
                │   └── citus.spec
                └── F-24
                    └── citus.spec

16 directories, 10 files
```

Looked through the `git` history and it appears the 9.4 files never existed?

**Comment by jasonmp85** [comment]
Closing this, as it appears the RPM PGDG repos _never_ had `citus_94`. I guess no one tried it (or contacted us about it, apparently)?
