### ISSUE TITLE
I can't seem to build

### ISSUE THREAD

**Issue by posix4e** [citusdata/packaging#2]
Should I be able to build this? Do I need some secret creds?

**Comment by jasonmp85** [comment]
Hey Alex. This repo is basically just the build chain we use to create Linux packages internally. Sorry for any confusion… I didn't realize someone might stumble across it and try to build externally. Or in other words, yes, you need some secret creds :smile:.

While building these scripts, I referenced a number of other public packaging repos for (often themselves private) PostgreSQL projects, so figured keeping this public would help others doing the same; however, I didn't really intend it to have any issues open against it, so going to turn off Issues for now.
