### ISSUE TITLE
Incorrect URL generated for postgres package repo on RHEL 6.4

### ISSUE THREAD

**Issue by samay-sharma** [citusdata/packaging#38]
I was with a prospect trying to install citus using the instructions present in [our docs](https://docs.citusdata.com/en/v6.1/installation/production_rhel.html)

After running the rpm.sh script, when we tried to run `sudo yum install -y citus61_96`, postgres installation failed. On investigating further, we were getting an error saying that `https://download.postgresql.org/pub/repos/yum/9.6/redhat/rhel-6.40-x86_64/repodata/repomd.xml` could not be found.

On further investigation, we found that the URL should be `https://download.postgresql.org/pub/repos/yum/9.6/redhat/rhel-6.4-x86_64/repodata/repomd.xml` (i.e without the 0). We manually changed the baseurl in `/etc/yum.repos.d/pgdg-96.redhat.repo` to `https://download.postgresql.org/pub/repos/yum/9.6/redhat/rhel-6.4-$basearch` and the installation of postgres and Citus went forward as expected.

I don't know what caused the incorrect URL but that might be related to our rpm.sh script as that was the only thing we had run until that point.

**Comment by hanefi** [comment]
PGDG repo paths occasionally change and this breaks our `rpm.sh` or `deb.sh` scripts.

`deb.sh` is tested everyday by a cronjob that installs nightly packages.
