### ISSUE TITLE
Config error on el/8 build process

### ISSUE THREAD

**Issue by gurkanindibay** [citusdata/packaging#591]
Error while building community citus as below
2021-01-28T19:24:53.4860923Z # remove the temporary gpg directory
2021-01-28T19:24:53.4861300Z rm -rf "$temp_gnupghome"
**2021-01-28T19:24:53.5107405Z /sbin/ldconfig: Warning: ignoring configuration file that cannot be opened: /etc/ld.so.conf: No such file or directory**
2021-01-28T19:24:53.8940707Z Processing files: citus-enterprise95_12-9.5.2.citus-1.el8.x86_64

**Comment by hanefi** [comment]
> Error while building **community** citus as below

> 2021-01-28T19:24:53.8940707Z Processing files: citus-**enterprise**95_12-9.5.2.citus-1.el8.x86_64

Can you share a link to the CI run? Your message seems to be for enterprise packages

**Comment by gurkanindibay** [comment]
error is ignorable
