### ISSUE TITLE
pg_auto_failover packages are missing -contrib dependencies

### ISSUE THREAD

**Issue by hanefi** [citusdata/packaging#592]
Devrim, pointed out an issue with our packages, and fixed it on PGDG packages. We should patch our rpm spec files to add missing dependencies.

> * The *community*  package is lacking -contrib dependency. I fixed it in 1.4.1 > update. Thanks for the report.

_Originally posted by @devrimgunduz in https://github.com/citusdata/pg_auto_failover/issues/558#issuecomment-749438443_

**Comment by gurkanindibay** [comment]
# Update OS Packages
  - [x] Make sure you have the latest tooling installed from the https://github.com/citusdata/tools repo, using `(sudo) make install`
  - [x] Go to your locally checked out version of the https://github.com/citusdata/packaging repo.
  - [x] Create a packaging PR using `update_os_package.pl all pgautofailover $VERSION`
  - [x] Test the release build locally: `citus_package -p=debian/buster  -p=debian/stretch -p=ubuntu/bionic -p=ubuntu/xenial -p ubuntu/focal -p=el/8   -p=el/7  -p=ol/7 local release 2>&1 | tee citus_package.log`
  - [ ] Confirm for some of the packages that the contents look decent using `dpkg -c package.deb` and `rpm -qlp package.rpm` 
  - [x] Ensure no warnings or errors are present: `grep -Ei '(warning|\bi|\be|\bw):' citus_package.log | sort | uniq -c | grep -v "\.c"`. Ignore any errors about `--disable-dependency-tracking`
  - [x] Get changes reviewed; 
  - [x] Confirm that CI is happy
  - [x] Use the "squash" strategy to close the PR
  - [x] Ensure both Travis builds completed successfully (new releases should be in packagecloud, you should expect 12 items when searching for new version)

**Comment by gurkanindibay** [comment]
#Enterprise  Update OS Packages
  - [x] Make sure you have the latest tooling installed from the https://github.com/citusdata/tools repo, using `(sudo) make install`
  - [x] Go to your locally checked out version of the https://github.com/citusdata/packaging repo.
  - [x] Create a packaging PR using `update_os_package.pl all pgautofailover-enterprise $VERSION`
  - [x] Test the release build locally: `citus_package -p=debian/buster -p=debian/jessie -p=debian/stretch -p=ubuntu/bionic -p=ubuntu/xenial -p ubuntu/focal -p=el/8 -p ol/8  -p=el/7 -p=el/6 -p=ol/7 -p=ol/6 local release 2>&1 | tee citus_package.log`
  - [x] Confirm for some of the packages that the contents look decent using `dpkg -c package.deb` and `rpm -qlp package.rpm` 
  - [x] Ensure no warnings or errors are present: `grep -Ei '(warning|\bi|\be|\bw):' citus_package.log | sort | uniq -c | grep -v "\.c"`. Ignore any errors about `--disable-dependency-tracking`
  - [x] Get changes reviewed; 
  - [x] Confirm that CI is happy
  - [x] Use the "squash" strategy to close the PR
  - [x] Ensure both Travis builds completed successfully  (new releases should be in packagecloud, you should expect 12items when searching for new version)

## Microsoft Packages

- [ ] Add vso (Visual Studio Online) remote to your local git checkout of the github packaging repo (only needed once):
`git remote add vso msdata@vs-ssh.visualstudio.com:v3/msdata/Database%20Systems/citus-packaging`
- [x] To trigger a test build on Azure DevOps:
`git checkout all-pgautofailover-enterprise`
`git pull # from normal github origin`
`git push vso # update Azure DevOps mirror`
- [x] Go here: https://msdata.visualstudio.com/Database%20Systems/_build?definitionId=10018&_a=summary
- [x] Wait for build to succeed. If build does not success, go here: 
https://msdata.visualstudio.com/Database%20Systems/_apps/hub/ms.vss-ciworkflow.build-ci-hub?_a=edit-build-definition&id=10018.
Maybe you need to update some parameters there (like the tools repo version). Then save it without queuing and then “Run pipeline” again via the first link.
- [x] Check that it created the right packages by looking at the logs and artifacts (the button with the box/drawer icon and text “9 published”).
  - [x] Click there, and see 7 items in signed packages
         centos 6/7/8
         debian buster/stretch
         ubuntu bionic/xenial         
  - [x] Check logs for each of 7 builds, by clicking `View raw log`
- [ ] Go back to the overview: https://msdata.visualstudio.com/Database%20Systems/_build?definitionId=10018&_a=summary
- [ ] Click “Run pipeline”
- [x] Click “Variables”
- [x] Change PUBLISH_TO_PACKAGE_REPO to “true”
- [x] Go back after doing so and click "Run”
- [x] Wait until completed.
- [x] Check if packages are successfully published using below links:
  ~~- [ ] ~8~ 10 new items for the version for Ubuntu (xenial and bionic): https://packages.microsoft.com/repos/citus-ubuntu/pool/main/p/pg-auto-failover-enterprise/~~
 ~~- [ ] ~12~ 10 new items for the version for Debian (~jessie,~ buster and stretch): https://packages.microsoft.com/repos/citus-debian/pool/main/p/pg-auto-failover-enterprise /~~
  ~~- [x] 3 new items for the version for CentOS6/RHEL6: https://packages.microsoft.com/yumrepos/citus-centos6/~~
  - [x] ~3~ 4 new items for the version for CentOS7/RHEL7: https://packages.microsoft.com/yumrepos/citus-centos7/
  - [x] ~3~ 4 new items for the version for CentOS8/RHEL8: https://packages.microsoft.com/yumrepos/citus-centos8/

**Comment by hanefi** [comment]
@gurkanindibay can we close this?
