### ISSUE TITLE
Fedora 25 7.0 package not found.

### ISSUE THREAD

**Issue by sumedhpathak** [citusdata/packaging#71]
AMI: Fedora-Cloud-Base-25-20170605.0.x86_64-us-east-1-PV-standard-0 (ami-00732316)

```
[fedora@ip-10-165-89-150 ~]$ sudo yum install -y citus70_96
Redirecting to '/usr/bin/dnf install -y citus70_96' (see 'man yum2dnf')

No package citus70_96 available.
Error: Unable to find a match.
```

I presume the dnf redirect is not the issue, but not sure. 

We also don't yet have Fedora 26, and Fedora's website https://alt.fedoraproject.org/cloud/ only promotes 26. 
Rather than fixing this, could we instead look at download stats for Fedora, and kill Fedora as a platform if the stats are low/negligible?

**Comment by sumedhpathak** [comment]
This is fixed now.

**Comment by jasonmp85** [comment]
Thanks for the verification!
