### ISSUE TITLE
E2E tests after releasing new packages 

### ISSUE THREAD

**Issue by hanefi** [citusdata/packaging#719]
After we create new packages for Citus, we should run some tests on all available platforms to make sure that the contents of the packages are ok.

Here is a possible list of steps that can be run on clean VMs:
- Using the steps in https://citusdata.com/download install the packages
- Create a local Citus cluster
- Connect to the database and run some SQL queries to test the basic functionality of citus

The scope:
- Create parallel tasks for
  - all available Linux flavors that are supported
  - all PG versions that are supported
- Install debug symbols, if any
  - test that debug symbols exist for executables and linkables
- Check that bytecode objects for JIT compilation are intact
- Check that versioning information is correct
	- `SHOW citus.version`
	- `SELECT citus_version()`
- Test docker images
	- test all different images and docker-compose
	- test basic functionality

**Comment by gurkanindibay** [comment]
https://github.com/citusdata/packaging/pull/838
https://github.com/citusdata/tools/pull/198
closed
