### ISSUE TITLE
Debug packages for ubuntu xenial is missing

### ISSUE THREAD

**Issue by gurkanindibay** [citusdata/packaging#732]
ubuntu focal and bionic has debug packages but xenial does not have debug packages.

**Comment by hanefi** [comment]
FYI, Ubuntu Xenial (16.04) had an EOL date of April, 2021.

It is safe to drop packages for said repo I guess.

**Comment by hanefi** [comment]
See https://endoflife.software/operating-systems/linux/ubuntu
