### ISSUE TITLE
Update Apt caches before installing packages in workflows

### ISSUE THREAD

**Issue by hanefi** [citusdata/packaging#734]
Github Actions docs have a note [here](https://docs.github.com/en/actions/using-github-hosted-runners/customizing-github-hosted-runners) :

> Note: Always run sudo apt-get update before installing a package. In case the apt index is stale, this command fetches and re-indexes any available packages, which helps prevent package installation failures.

Before working on this task, make sure you create a list of all branches with yaml files in all our repos and create a checklist.

**Comment by gurkanindibay** [comment]
I checked all pipelines under docker/.github, tools/github, packaging/all-citus,packaging/all-enterprise, packaging/all-pgautofailover, packaging/all-pgautofailover-enterprise, packaging/debian-hll, packaging/redhat-hll,   packaging/debian-topn, packaging/redhat-topn,packaging/debian-cron, packaging/redhat-cron,packaging/pgxn-citus
and all have apt-cache
